services:

    amulen.classification.form.category:
        class: Flowcode\ClassificationBundle\Form\CategoryType
        tags:
            - { name: form.type, alias: amulen_classificationbundle_category }

    amulen.classification.form.collection:
        class: Flowcode\ClassificationBundle\Form\CollectionType
        tags:
            - { name: form.type, alias: amulen_classificationbundle_collection }

    amulen.classification.form.tag:
        class: Flowcode\ClassificationBundle\Form\TagType
        tags:
            - { name: form.type, alias: amulen_classificationbundle_tag }

    amulen.classification.category:
        class: Flowcode\ClassificationBundle\Service\CategoryService
        arguments: ["@service_container"]

    amulen.classification.showmenu_eventsubscriber:
        class: Flowcode\ClassificationBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }
        