<?php

namespace Flowcode\ClassificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{

    public function findEnabled($order = 'ASC')
    {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.enabled = 1');
        $qb->orderBy('c.position', $order);

        return $qb->getQuery()->getResult();
    }

}
